// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFEuPSWRTqm9mfE5SpNnAsD6AvP6g-x8',
    appId: '1:1031155975102:web:f26cef1ec8864f96df2fef',
    messagingSenderId: '1031155975102',
    projectId: 'forty-two-6128c',
    authDomain: 'forty-two-6128c.firebaseapp.com',
    storageBucket: 'forty-two-6128c.appspot.com',
    measurementId: 'G-LGH1BD0JR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_w6g0RFpEfyWN-aY-B9eH6saEKKnZJ10',
    appId: '1:1031155975102:android:7265cc5dbd32a9e1df2fef',
    messagingSenderId: '1031155975102',
    projectId: 'forty-two-6128c',
    storageBucket: 'forty-two-6128c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQBorqm68Zp7LHRIxxIxNwZD8hO46JDrE',
    appId: '1:1031155975102:ios:ae3413242d2391ecdf2fef',
    messagingSenderId: '1031155975102',
    projectId: 'forty-two-6128c',
    storageBucket: 'forty-two-6128c.appspot.com',
    iosBundleId: 'com.app.fortytwo.fortytwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQBorqm68Zp7LHRIxxIxNwZD8hO46JDrE',
    appId: '1:1031155975102:ios:ae3413242d2391ecdf2fef',
    messagingSenderId: '1031155975102',
    projectId: 'forty-two-6128c',
    storageBucket: 'forty-two-6128c.appspot.com',
    iosBundleId: 'com.app.fortytwo.fortytwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuFEuPSWRTqm9mfE5SpNnAsD6AvP6g-x8',
    appId: '1:1031155975102:web:46031c31e49378a9df2fef',
    messagingSenderId: '1031155975102',
    projectId: 'forty-two-6128c',
    authDomain: 'forty-two-6128c.firebaseapp.com',
    storageBucket: 'forty-two-6128c.appspot.com',
    measurementId: 'G-WGEZ3X0G7E',
  );

}